apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-prediction-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ali-stack261/stock.git'
    path: kubernetes/staging
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-prediction-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ali-stack261/stock.git'
    path: kubernetes/production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
